### ISSUE TITLE
Not existing input file should be handled

### ISSUE THREAD

**Issue by vbfox** [vbfox/stidgen#16]
Currently throw an exception

**Comment by vbfox** [comment]
Not cool :

```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'c:\test'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at BlackFox.Stidgen.ConfigurationParser.loadFromFile(FileInfo file)
   at BlackFox.Stidgen.FileGeneration.generateToFiles(String configurationPath)
   at BlackFox.Stidgen.Program.main(String[] argv)
```

**Comment by vbfox** [comment]
The exception doesn't exists anymore but in the current code there is no feedback for invalid file

**Comment by vbfox** [comment]
Done in 9fb9066ace35f859036255d47ec7738e42c8f8b6
